import Navbar from "../components/Navbar";

export default function About() {
  return (
    <>
      <Navbar />

      <div className="min-h-[calc(100vh-64px)] bg-green-50 px-6 py-12 flex justify-center pt-24">
        <div className="max-w-4xl bg-white p-8 rounded-xl shadow">
          <h1 className="text-3xl font-bold text-green-700 mb-6 text-center">
            About GreenStep 🌱
          </h1>

          <p className="text-gray-700 mb-4 leading-relaxed">
            <strong>GreenStep</strong> is a personal carbon footprint tracker
            designed to help individuals understand how their daily activities
            impact the environment.
          </p>

          <p className="text-gray-700 mb-4 leading-relaxed">
            A <strong>carbon footprint</strong> represents the total amount of
            greenhouse gases (mainly CO₂) generated by human activities such as
            transportation, food habits, and energy consumption.
          </p>

          <p className="text-gray-700 mb-4 leading-relaxed">
            By calculating your footprint, GreenStep empowers you to take
            informed steps toward reducing emissions and living sustainably.
          </p>

          <h2 className="text-2xl font-semibold text-green-600 mt-8 mb-3">
            Why Carbon Footprint Matters?
          </h2>

          <ul className="list-disc pl-6 text-gray-700 space-y-2">
            <li>Climate change and global warming</li>
            <li>Air pollution and health impacts</li>
            <li>Melting glaciers and rising sea levels</li>
            <li>Loss of biodiversity</li>
          </ul>

          <p className="text-gray-700 mt-6">
            Small changes in lifestyle can make a big difference.  
            <strong> GreenStep helps you start that journey.</strong>
          </p>
        </div>
      </div>
    </>
  );
}
